os: "linux"
arch: "amd64"

vip: 192.168.0.1
interface: enp6s67
kubeconfig: /etc/rancher/rke2/rke2.yaml
containerd_address: /run/k3s/containerd/containerd.sock
containerd_runtime_endpoint: unix:///run/k3s/containerd/containerd.sock

ansible_become: true
ansible_become_method: sudo